### PR TITLE
feat: include epochs 2.5 and 3.0 in generated Stacks.toml

### PR DESCRIPTION
**Pull request by obycode**
This adds support to include the start height for epochs 2.5 and 3.0 in the Stacks.toml generated for devnet.

### CODE REVIEW

**Comment by obycode** [comment]
I fixed some issues in https://github.com/stacks-network/stacks-core/pull/4138.

Next step is to add some pox-4 stackers so we can start epoch 3.0!

**Comment by lgalabru** [comment]
Thanks @obycode! It'd be great to ignore the 101 first blocks that I was experiencing earlier. 
It should be a one liner stacks-node but it saves a bunch of seconds of initialization time for developers (very valuable when you're in a manual, caveman debugging cycle test / retry / test / retry / ...)

**Comment by hugocaillard** [comment]
@obycode I cherry-picked the commits in #1266

**Comment by obycode** [comment]
Great! So we can close this one?

**Comment by hugocaillard** [comment]
Yes 👍

**Pull request closed without merging**
