### PR TITLE
Update faq.md: FAQ's -> FAQs

### PR DESCRIPTION
**Pull request by saralab**
FAQs NOT FAQ's

### CODE REVIEW

**Review by hugocaillard — APPROVED** [review]
LGTM 
Thanks Sarala

**Comment by hugocaillard** [comment]
@aravindgee Is it possible that the actions don't run because it's a .md file, but then it prevents us from merging? 🤔

**Comment by aravindgee** [comment]
@hugocaillard , yes, [this is because of the filter](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks) to skip the docs directory. I've merged the PR with bypassing branch rules.

**Comment by hugocaillard** [comment]
@aravindgee Ah. But can we make it work without bypassing branch protection?
I'd like to have it working for future PRs as well

**Comment by aravindgee** [comment]
Hi @hugocaillard happy to assist but I need to investigate this a bit. would you mind creating an issue on the devops board? if this isn't a priority item, we will get to it during a future planning iteration.

**Comment by hugocaillard** [comment]
hey @aravindgee 
Thanks for you help. 
I tried to find a solution and it looks like a solution is to create a script in the workflow that'll call the github API and check if the PR contains changes on .md files. 

But it might be overkill for now.

I'll remember to open an issue on the devops board eventually. We'll have some work to do on our CI in the coming weeks/months anyway 👍 

Thx!

**Pull request merged**
