### PR TITLE
feat: cost reporting via tests

### PR DESCRIPTION
**Pull request by lgalabru**
This PR starts addressing https://github.com/hirosystems/clarinet/issues/41, by introducing a flag `--cost` that can be passed when running tests.

```bash
➜  counter git:(feat/cost-tracking) ✗ clarinet test --costs

Running file:///Users/ludovic/Coding/clarinet/clarinet-cli/examples/counter/tests/counter_test.ts
* Ensure that counter can be incremented multiples per block, accross multiple blocks ... ok (24ms)

Contract calls cost synthesis
+-----------+------------+------------+-----------------+-------------+----------------+--------------+
| ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.counter::increment                                        |
+-----------+------------+------------+-----------------+-------------+----------------+--------------+
|           | Runtime    | Read Count | Read Length     | Write Count | Write Length   | Tx per Block |
+-----------+------------+------------+-----------------+-------------+----------------+--------------+
| Max       | 838000     | 5          | 613 bytes       | 1           | 17 bytes       | 1550         |
+-----------+------------+------------+-----------------+-------------+----------------+--------------+
| ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.counter::read-counter                                     |
+-----------+------------+------------+-----------------+-------------+----------------+--------------+
|           | Runtime    | Read Count | Read Length     | Write Count | Write Length   | Tx per Block |
+-----------+------------+------------+-----------------+-------------+----------------+--------------+
| Max       | 617000     | 4          | 613 bytes       | 0           | 0 bytes        | 1937         |
+-----------+------------+------------+-----------------+-------------+----------------+--------------+
| Block Limits                                                                                        |
+-----------+------------+------------+-----------------+-------------+----------------+--------------+
| Mainnet   | 5000000000 | 7750       | 100000000 bytes | 7750        | 15000000 bytes | /            |
+-----------+------------+------------+-----------------+-------------+----------------+--------------+
```

The costs for every method explicitly invoked when mining tests blocks
```
        let block = chain.mineBlock([
            Tx.contractCall("counter", "increment", [types.uint(1)], wallet_1.address),
            ...
        ]);
 ```
are collected, and rendered in the terminal. If multiple invocations for a given method were collected, the most expensive instance is being displayed.

### CODE REVIEW

**Comment by kyranjamie** [comment]
abbreviated flag `-c` 🤔

**Comment by LNow** [comment]
This looks great!!
Would it be possible to add % values to this report? So that we won't have to calculate it on a side, to find out if our contract will eat 0.01% or 10% of a whole block execution costs limits.

**Comment by lgalabru** [comment]
@LNow already, the latest version of the reports looks like this:

Screen Shot 2021-09-15 at 4 06 12 PM

**Comment by LNow** [comment]
I love it. @whoabuddy look at this!

**Comment by lgalabru** [comment]
https://user-images.githubusercontent.com/87777/133644416-74e671b1-a5bf-4bb4-a64f-ba883c0ee915.mov

**Comment by unclemantis** [comment]
Please build into windows binary .msi file. I downloaded the recent msi for x63 and the --costs flag does not work.

Thank you!!!!

**Pull request merged**
