### PR TITLE
MacOS arm64 / Apple Silicon support

### PR DESCRIPTION
**Pull request by zone117x**
Closes https://github.com/hirosystems/clarinet/issues/210

### CODE REVIEW

**Review by obycode — APPROVED** [review]
Looks good. Thanks @zone117x!

I noticed that the 0.25.0 release page only has assets for linux-x64. Do you know why the darwin-x64 and windows-x64 assets aren't there?

**Comment by obycode** [comment]
Oh, ignore my question. I noticed the actions are still running - https://github.com/hirosystems/clarinet/actions/runs/1825565418

**Comment by obycode** [comment]
I had to force push to develop to solve an ugly conflict between main and develop, so you'll need to rebase this branch. Sorry about that.

**Comment by zone117x** [comment]
@obycode no worries. Do you have an M1 and able to test the artifacts? The CI tests for macos-arm64 are disabled, and I only did basic sanity checks on my end.

**Review by obycode — APPROVED** [review]
👍

**Pull request merged**
