### PR TITLE
Subnet updates

### PR DESCRIPTION
**Pull request by obycode**
This PR contains various minor updates related to subnet support.

### CODE REVIEW

**Review by hugocaillard — DISMISSED** [review]
LGTM ✅ 
Seems pretty safe to be merge.
cc @lgalabru in case you want to have a look as well.

@obycode Does it need to be released soon(ish)?

**Comment by obycode** [comment]
Most of it is just "nice to have" soon, but not urgent, since it is just setting defaults that can be overridden in the config file. However, there is not currently any way to set these new environment variables for the subnet API node without also setting them for the Stacks API node, so that would be helpful to release soon.

```
            format!("STACKS_CHAIN_ID=0x55005500"),
            format!("CUSTOM_CHAIN_IDS=testnet=0x55005500"),
```

**Review by lgalabru — APPROVED** [review]
Thanks @obycode!
@MicaiahReid I hope this does not conflict too much with your work!

**Comment by MicaiahReid** [comment]
@lgalabru It shouldn't be too bad!

**Comment by jbencin** [comment]
Just updated a couple of constants, but need re-approval to merge now

**Review by hugocaillard — APPROVED** [review]

**Comment by hugocaillard** [comment]
I approved and enabled auto merge.
cc @MicaiahReid @lgalabru

**Pull request merged**
