### PR TITLE
Deleted the Image and added the new youtube playlist link

### PR DESCRIPTION
**Pull request by RajeevDash007**
### Description

https://github.com/hirosystems/docs/issues/424
### Example

---

### Checklist

- [ ] Tests added in this PR (if applicable)

### CODE REVIEW

**Comment by RajeevDash007** [comment]
@LakshmiLavanyaKasturi check this out

**Review by LakshmiLavanyaKasturi — APPROVED** [review]

**Comment by hugocaillard** [comment]
Hello @RajeevDash007 
Thanks for you contribution!
Can you sign the CLA please?

**Comment by RajeevDash007** [comment]
> Hello @RajeevDash007 Thanks for you contribution! Can you sign the CLA please?

@hugocaillard how can I do that?
can you provide me the file link?

**Comment by hugocaillard** [comment]
@RajeevDash007 https://github.com/hirosystems/clarinet/pull/1126#issuecomment-1674573397

**Pull request merged**
