### PR TITLE
fixed links to documentation inside the application

### PR DESCRIPTION
**Pull request by criadoperez**
Using the clarinet application you sometimes get links to documentation that are broken.
Fixed the links to the working ones.

### CODE REVIEW

**Review by obycode — APPROVED** [review]
Thank you!

**Comment by criadoperez** [comment]
I just realized I made this PR to the *main* branch instead of *develop* branch. Should I change it to *develop*?

**Comment by obycode** [comment]
Yes, thanks. I missed that too.

**Comment by obycode** [comment]
Also, please run `cargo fmt` and re-commit -- see the [failing CI job](https://github.com/hirosystems/clarinet/runs/4845051949?check_suite_focus=true).

**Comment by criadoperez** [comment]
> Yes, thanks. I missed that too.

ok, changed.

**Comment by criadoperez** [comment]
> Also, please run `cargo fmt` and re-commit -- see the [failing CI job](https://github.com/hirosystems/clarinet/runs/4845051949?check_suite_focus=true).

will do

**Comment by criadoperez** [comment]
run successfully `cargo build`, `cargo test` and `cargo fmt --all --`

**Review by obycode — APPROVED** [review]

**Pull request merged**
