### PR TITLE
Quick discord link fix

### PR DESCRIPTION
**Pull request by diempi**

### CODE REVIEW

**Comment by diempi** [comment]
> Thanks for this contribution @diempi! Where did you get that one? Is seems to be a link generated by Brice. I don't know if such links expire. We could try this one that is the one from the stacks foundation website: `https://discord.gg/HsK3ShU`

Hello Hugo, 
I found that one on the website Hiro.so (at the bottom in the links), indeed I had a hardtime finding a good link haha
Cheers

**Comment by hugocaillard** [comment]
Alright then, if Brice made it to the hiro.so footer, we can give him clarinet as well :D 

Thx @diempi

**Review by hugocaillard — APPROVED** [review]
LGTM @diempi 
Thx

**Comment by diempi** [comment]
You are welcome and thank you

**Pull request merged**
