### PR TITLE
clarity format

### PR DESCRIPTION
**Pull request by hugocaillard**

### CODE REVIEW

**Comment by lgalabru** [comment]
Looking great! how would you feel about using the structure that we have in place in this PR https://github.com/hirosystems/clarinet/pull/664? You could get rid of the initial visitor approach, but keep the dedicated component boilerplate?

**Comment by hugocaillard** [comment]
> but keep the dedicated component boilerplate

Yep I'll definitely reuse the component boilerplate 👍 (and maybe the ast visitor, need to think about it)

**Comment by lgalabru** [comment]
I am going to close https://github.com/hirosystems/clarinet/pull/664 in favor of this one, but I will leave the underlying git branch available for the component boilerplate parts.

**Comment by hugocaillard** [comment]
Closing in favor of #914

**Pull request closed without merging**
